import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { headers } from "next/headers";
import Header from "@/components/Header";
import HomePage from "@/components/HomePage";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const isSurveyPage = headers().get('survey-page'); // null or true

  return (
    <>
      <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            {isSurveyPage ? <></> : <Header />}
            <main>
              {children}
            </main>
          </body>
        </html>
      </ClerkProvider>
    </>
  );
}
