import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { headers } from "next/headers";
import Header from "@/components/Header";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const url = headers().get('x-url'); // this header we set in middleware -> its pirpose is to not load header on survey page

  return (
    <>
      <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            {url ? <></> : <Header />}
            <main>
              {children}
            </main>
          </body>
        </html>
      </ClerkProvider>
    </>
  );
}
